"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, FileText, File, Plus, Pencil, Trash2, X, Upload, Search, Check } from "lucide-react";
import { Shell } from "@/components/shell";
import { HistoricalPanel } from "@/components/historical-panel";
import { HistoricalImagePanel } from "@/components/historical-image-panel";
import { WebResearchPanel } from "@/components/web-research-panel";
import { InvestigationAgentPanel } from "@/components/investigation-agent-panel";
import { CorrelationPanel } from "@/components/correlation-panel";
import { TimelinePanel } from "@/components/timeline-panel";
import { GeospatialPanel } from "@/components/geospatial-panel";
import { ContradictionsPanel } from "@/components/contradictions-panel";
import { api } from "@/lib/api";
import type { Evidence, Investigation, InvestigationStatus } from "@/lib/types";

const future=["Web Research","Sources","Timeline","Evidence Graph","Contradictions","Research Gaps","AI Findings","Report"];
type Filter = "ALL" | "TEXT" | "IMAGE" | "DOCUMENT";

export default function InvestigationDetail(){
  const {id}=useParams<{id:string}>();const router=useRouter();
  const [item,setItem]=useState<Investigation|null>(null);const [error,setError]=useState("");const [edit,setEdit]=useState(false);const [saving,setSaving]=useState(false);
  const [evidence,setEvidence]=useState<Evidence[]|null>(null);const [evidenceError,setEvidenceError]=useState("");const [filter,setFilter]=useState<Filter>("ALL");const [query,setQuery]=useState("");const [modal,setModal]=useState(false);const [selected,setSelected]=useState<Evidence|null>(null);const [notice,setNotice]=useState("");const [evidenceRefresh,setEvidenceRefresh]=useState(0);const [agentRefresh,setAgentRefresh]=useState(0);const refreshResearch=useCallback(()=>setAgentRefresh(value=>value+1),[]);
  const loadEvidence=useCallback(()=>{setEvidence(null);setEvidenceError("");api.evidence(id,filter==="ALL"?undefined:{type:filter}).then(setEvidence).catch((e:Error)=>setEvidenceError(e.message))},[id,filter]);
  useEffect(()=>{api.investigation(id).then(setItem).catch((e:Error)=>setError(e.message))},[id]);
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("edit")==="1")setEdit(true)},[]);
  useEffect(()=>{loadEvidence()},[loadEvidence]);
  async function submit(e:FormEvent){e.preventDefault();if(!item)return;setSaving(true);setError("");try{const updated=await api.patch<Investigation>(`/investigations/${id}`,{title:item.title,description:item.description,status:item.status});setItem(updated);setEdit(false);router.replace(`/investigations/${id}`)}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
  async function removeEvidence(record:Evidence){if(!window.confirm(`Delete “${record.title}”? This will remove this evidence item from the investigation.`))return;try{await api.deleteEvidence(record.id);setSelected(null);setNotice("Evidence deleted.");loadEvidence();setEvidenceRefresh(value=>value+1)}catch(e){setEvidenceError((e as Error).message)}}
  const visible=(evidence||[]).filter(e=>`${e.title} ${e.description} ${e.original_filename||""}`.toLowerCase().includes(query.toLowerCase()));
  return <Shell><Link className="back" href="/investigations"><ArrowLeft size={15}/> Investigations</Link>{error&&<p className="error">{error}</p>}{!item&&!error&&<p className="hint">Loading investigation...</p>}{item&&<><header className="topbar"><div><span className="eyebrow">INVESTIGATION WORKSPACE</span><h1>{item.title}</h1></div><button className="button secondary" onClick={()=>setEdit(!edit)}><Pencil size={15}/> {edit?"Cancel":"Edit"}</button></header>{edit?<form className="form-card" onSubmit={submit}><label>Title<input required maxLength={240} value={item.title} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>Description<textarea rows={5} maxLength={10000} value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></label><label>Status<select value={item.status} onChange={e=>setItem({...item,status:e.target.value as InvestigationStatus})}>{["DRAFT","ACTIVE","COMPLETED","ARCHIVED"].map(x=><option key={x}>{x}</option>)}</select></label>{error&&<p className="error">{error}</p>}<button className="button" disabled={saving}>{saving?"Saving…":"Save changes"}</button></form>:<><div className="detail-card"><div><span className="eyebrow">STATUS</span><p className="status">{item.status}</p></div><div><span className="eyebrow">CREATED</span><p>{new Date(item.created_at).toLocaleString()}</p></div><div><span className="eyebrow">LAST UPDATED</span><p>{new Date(item.updated_at).toLocaleString()}</p></div><div className="description"><span className="eyebrow">DESCRIPTION</span><p>{item.description||"No description has been added."}</p></div></div>
    <section className="evidence-section"><div className="section-head"><div><span className="eyebrow">CASE MATERIAL</span><h3>Evidence <span className="evidence-count">{evidence?.length??"—"}</span></h3></div><button className="button" onClick={()=>{setModal(true);setNotice("")}}><Plus size={16}/> Add evidence</button></div>
      {notice&&<p className="success"><Check size={14}/>{notice}</p>}{evidenceError&&<p className="error">{evidenceError}</p>}
      <div className="evidence-toolbar"><label className="evidence-search"><Search size={15}/><input placeholder="Search evidence…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{(["ALL","TEXT","IMAGE","DOCUMENT"] as Filter[]).map(x=><button key={x} className={filter===x?"filter active":"filter"} onClick={()=>setFilter(x)}>{x==="ALL"?"All":x==="IMAGE"?"Images":x==="DOCUMENT"?"Documents":"Text"}</button>)}</div></div>
      {evidence===null&&!evidenceError&&<div className="loading-box">Loading evidence…</div>}{evidence&&visible.length===0&&<div className="empty evidence-empty"><div className="empty-icon"><FileText size={20}/></div><h4>{query?"No matching evidence":"No evidence added yet"}</h4><p>{query?"Try a different search term.":"Add statements, images, documents, and other case material to begin building the evidence base."}</p>{!query&&<button className="button" onClick={()=>setModal(true)}><Plus size={16}/> Add evidence</button>}</div>}
      {evidence&&visible.length>0&&<div className="evidence-grid">{visible.map(record=><button id={`evidence-${record.id}`} className="evidence-card" key={record.id} onClick={()=>setSelected(record)}><div className="evidence-thumb">{record.type==="IMAGE"?<img src={api.evidenceContentUrl(record.id)} alt=""/>:record.type==="TEXT"?<FileText size={21}/>:record.type==="DOCUMENT"?<File size={21}/>:<FileText size={21}/>}</div><div className="evidence-card-body"><div className="evidence-card-top"><span className="eyebrow">{record.type.replace("_"," ")}</span><span className="processing">{record.processing_status}</span></div><strong>{record.title}</strong><p>{record.description||record.text_content?.slice(0,130)||record.original_filename||"No description"}</p><div className="evidence-card-meta"><span>{new Date(record.created_at).toLocaleDateString()}</span>{record.original_filename&&<span className="filename">{record.original_filename}</span>}</div></div></button>)}</div>}
    </section><HistoricalPanel investigationId={id} refreshKey={evidenceRefresh}/><HistoricalImagePanel investigationId={id} refreshKey={evidenceRefresh}/><WebResearchPanel investigationId={id} evidence={evidence || []} refreshKey={agentRefresh}/><InvestigationAgentPanel investigationId={id} onResearchUpdated={refreshResearch}/><CorrelationPanel investigationId={id} evidence={evidence||[]}/><TimelinePanel investigationId={id}/><GeospatialPanel investigationId={id}/><ContradictionsPanel investigationId={id}/><div className="section-head"><div><span className="eyebrow">ANALYSIS WORKSPACE</span><h3>Investigation modules</h3></div></div><div className="module-grid">{future.filter(name=>name!=="Web Research"&&name!=="Sources"&&name!=="Timeline"&&name!=="Investigation Agent"&&name!=="Evidence Correlation"&&name!=="Contradictions").map(name=><div className="module" key={name}><strong>{name}</strong><small>Coming in next analysis phases</small></div>)}</div></>}</>}
    {modal&&<EvidenceModal investigationId={id} onClose={()=>setModal(false)} onCreated={()=>{setModal(false);setNotice("Evidence added to this investigation.");loadEvidence();setEvidenceRefresh(value=>value+1)}}/>}
    {selected&&<EvidenceDetail record={selected} onClose={()=>setSelected(null)} onDelete={()=>removeEvidence(selected)}/>}
  </Shell>
}

function EvidenceModal({investigationId,onClose,onCreated}:{investigationId:string;onClose:()=>void;onCreated:()=>void}){
  const [mode,setMode]=useState<"TEXT"|"FILE">("TEXT");const [title,setTitle]=useState("");const [description,setDescription]=useState("");const [text,setText]=useState("");const [file,setFile]=useState<File|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{if(mode==="TEXT")await api.createTextEvidence(investigationId,{title,description,text_content:text});else if(file)await api.uploadEvidence(investigationId,file,title,description);else throw new Error("Choose a file to upload.");onCreated()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="add-evidence-title"><header className="dialog-head"><div><span className="eyebrow">CASE MATERIAL</span><h2 id="add-evidence-title">Add evidence</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></header><div className="mode-tabs"><button type="button" className={mode==="TEXT"?"mode active":"mode"} onClick={()=>setMode("TEXT")}><FileText size={15}/>Text</button><button type="button" className={mode==="FILE"?"mode active":"mode"} onClick={()=>setMode("FILE")}><Upload size={15}/>Upload file</button></div><form className="evidence-form" onSubmit={submit}><label>Title<input required maxLength={240} value={title} onChange={e=>setTitle(e.target.value)} placeholder="Evidence title"/></label><label>Description <span>Optional</span><textarea rows={3} maxLength={10000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="Context about this material"/></label>{mode==="TEXT"?<label>Text content<textarea required rows={8} maxLength={200000} value={text} onChange={e=>setText(e.target.value)} placeholder="Enter statement, note, or other text evidence"/></label>:<label className="file-drop"><Upload size={20}/><strong>{file?.name||"Choose a file"}</strong><span>JPEG, PNG, WebP, PDF, or UTF-8 text · max {process.env.NEXT_PUBLIC_MAX_EVIDENCE_FILE_SIZE_MB||15} MB</span><input type="file" accept="image/jpeg,image/png,image/webp,application/pdf,text/plain,.jpg,.jpeg,.png,.webp,.pdf,.txt" onChange={e=>setFile(e.target.files?.[0]||null)}/></label>}{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="button" disabled={busy||!title.trim()||(mode==="TEXT"&&!text.trim())||(mode==="FILE"&&!file)}>{busy?"Saving…":mode==="TEXT"?"Save evidence":"Upload evidence"}</button></div></form></section></div>
}

function EvidenceDetail({record,onClose,onDelete}:{record:Evidence;onClose:()=>void;onDelete:()=>void}){
  const size=record.file_size===null?"—":record.file_size<1024?`${record.file_size} B`:`${(record.file_size/1024/1024).toFixed(2)} MB`;
  return <div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dialog detail-dialog" role="dialog" aria-modal="true"><header className="dialog-head"><div><span className="eyebrow">{record.type.replace("_"," ")} · {record.processing_status}</span><h2>{record.title}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X size={18}/></button></header><p className="evidence-description">{record.description||"No description provided."}</p><div className="detail-evidence-grid"><div><span className="eyebrow">CREATED</span><p>{new Date(record.created_at).toLocaleString()}</p></div><div><span className="eyebrow">UPDATED</span><p>{new Date(record.updated_at).toLocaleString()}</p></div><div><span className="eyebrow">FILENAME</span><p>{record.original_filename||"Entered text"}</p></div><div><span className="eyebrow">MIME TYPE</span><p>{record.mime_type||"text/plain"}</p></div><div><span className="eyebrow">SIZE</span><p>{size}</p></div><div><span className="eyebrow">SHA-256</span><p className="checksum">{record.checksum||"—"}</p></div></div>{record.type==="TEXT"?<div className="text-preview">{record.text_content}</div>:record.type==="IMAGE"?<img className="large-preview" src={api.evidenceContentUrl(record.id)} alt={record.title}/>:<a className="button secondary download" href={api.evidenceContentUrl(record.id)}>Download file</a>}<div className="detail-actions"><button className="button danger" onClick={onDelete}><Trash2 size={15}/> Delete evidence</button></div></section></div>
}
