"""Add source-backed investigation timeline."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="0008_timeline_engine"
down_revision="0007_evidence_correlations"
branch_labels=None
depends_on=None

def upgrade():
    u=postgresql.UUID(as_uuid=True)
    op.create_table("timeline_events",
      sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("title",sa.String(500),nullable=False),sa.Column("description",sa.Text(),server_default="",nullable=False),sa.Column("event_type",sa.String(32),nullable=False),sa.Column("date_start",sa.Date(),nullable=True),sa.Column("date_end",sa.Date(),nullable=True),sa.Column("date_precision",sa.String(16),nullable=False),sa.Column("date_text",sa.String(500),server_default="",nullable=False),sa.Column("publication_date_start",sa.Date(),nullable=True),sa.Column("publication_date_end",sa.Date(),nullable=True),sa.Column("location",sa.String(500),nullable=True),sa.Column("normalized_location",sa.String(500),nullable=True),sa.Column("source_type",sa.String(32),nullable=True),sa.Column("source_id",u,nullable=True),sa.Column("historical_case_id",u,nullable=True),sa.Column("correlation_ids",postgresql.JSONB(astext_type=sa.Text()),server_default=sa.text("'[]'::jsonb"),nullable=False),sa.Column("importance",sa.String(16),server_default="MEDIUM",nullable=False),sa.Column("status",sa.String(24),server_default="AI_EXTRACTED",nullable=False),sa.Column("created_by",sa.String(24),server_default="AI",nullable=False),sa.Column("extraction_hash",sa.String(64),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["historical_case_id"],["historical_cases.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"),sa.CheckConstraint("date_end IS NULL OR date_start IS NULL OR date_end >= date_start",name="ck_timeline_date_order"),sa.CheckConstraint("event_type IN ('CASE_CREATED','INCIDENT','EVIDENCE_COLLECTED','PERSON_REPORTED','LOCATION_REPORTED','SEARCH_RESULT','NEWS_REPORT','HISTORICAL_CASE','PUBLICATION','INVESTIGATOR_NOTE','OTHER')",name="ck_timeline_event_type"),sa.CheckConstraint("date_precision IN ('EXACT','DAY','MONTH','YEAR','RANGE','APPROXIMATE','UNKNOWN')",name="ck_timeline_precision"),sa.CheckConstraint("source_type IS NULL OR source_type IN ('EVIDENCE','HISTORICAL_CASE','WEB_RESULT','NEWS_RESULT','IMAGE_RESULT','SOURCE','INVESTIGATOR')",name="ck_timeline_source_type"),sa.CheckConstraint("importance IN ('LOW','MEDIUM','HIGH')",name="ck_timeline_importance"),sa.CheckConstraint("status IN ('AI_EXTRACTED','INVESTIGATOR_ADDED','REVIEWED','DISMISSED')",name="ck_timeline_status"))
    op.create_index("ix_timeline_events_investigation_id","timeline_events",["investigation_id"]);op.create_index("ix_timeline_events_extraction_hash","timeline_events",["extraction_hash"])
    op.create_table("timeline_event_sources",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("timeline_event_id",u,nullable=False),sa.Column("source_type",sa.String(32),nullable=False),sa.Column("source_id",u,nullable=False),sa.Column("relationship_type",sa.String(24),server_default="SUPPORTING_SOURCE",nullable=False),sa.Column("content_hash",sa.String(64),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["timeline_event_id"],["timeline_events.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("timeline_event_id","source_type","source_id",name="uq_timeline_event_source"));op.create_index("ix_timeline_event_sources_timeline_event_id","timeline_event_sources",["timeline_event_id"])
    op.create_table("timeline_event_evidence",sa.Column("timeline_event_id",u,nullable=False),sa.Column("evidence_id",u,nullable=False),sa.Column("relationship_type",sa.String(24),server_default="SUPPORTING_EVIDENCE",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["timeline_event_id"],["timeline_events.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["evidence_id"],["evidence.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("timeline_event_id","evidence_id"))

def downgrade():
    op.drop_table("timeline_event_evidence");op.drop_index("ix_timeline_event_sources_timeline_event_id",table_name="timeline_event_sources");op.drop_table("timeline_event_sources");op.drop_index("ix_timeline_events_extraction_hash",table_name="timeline_events");op.drop_index("ix_timeline_events_investigation_id",table_name="timeline_events");op.drop_table("timeline_events")
