"""Add geospatial locations and source conflict records."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="0009_geospatial_contradictions"
down_revision="0008_timeline_engine"
branch_labels=None
depends_on=None

def upgrade():
    u=postgresql.UUID(as_uuid=True); jsonb=postgresql.JSONB(astext_type=sa.Text())
    op.create_table("locations",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("raw_text",sa.String(1000),nullable=False),sa.Column("normalized_name",sa.String(1000),nullable=False),sa.Column("latitude",sa.Float(),nullable=True),sa.Column("longitude",sa.Float(),nullable=True),sa.Column("precision",sa.String(24),nullable=False),sa.Column("geocoding_status",sa.String(24),nullable=False),sa.Column("geocoding_source",sa.String(120),nullable=True),sa.Column("geocoding_provider",sa.String(120),nullable=True),sa.Column("confidence_label",sa.String(16),nullable=False),sa.Column("country",sa.String(200),nullable=True),sa.Column("state",sa.String(200),nullable=True),sa.Column("district",sa.String(200),nullable=True),sa.Column("city",sa.String(200),nullable=True),sa.Column("locality",sa.String(300),nullable=True),sa.Column("metadata",jsonb,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("investigation_id","normalized_name","raw_text",name="uq_location_investigation_raw_normalized"),sa.CheckConstraint("precision IN ('EXACT_POINT','STREET','NEIGHBORHOOD','LOCALITY','CITY','DISTRICT','STATE','COUNTRY','REGION','APPROXIMATE','UNKNOWN')",name="ck_location_precision"),sa.CheckConstraint("geocoding_status IN ('PENDING','GEOCODED','PARTIAL','FAILED','NOT_FOUND','NOT_ATTEMPTED')",name="ck_location_geocoding_status"),sa.CheckConstraint("confidence_label IN ('HIGH','MEDIUM','LOW','UNKNOWN')",name="ck_location_confidence"),sa.CheckConstraint("(latitude IS NULL AND longitude IS NULL) OR (latitude BETWEEN -90 AND 90 AND longitude BETWEEN -180 AND 180)",name="ck_location_coordinates"))
    op.create_index("ix_locations_investigation_id","locations",["investigation_id"]);op.create_index("ix_locations_normalized_name","locations",["normalized_name"])
    links=[("timeline_event_locations","timeline_event_id","timeline_events","uq_timeline_location_link"),("evidence_locations","evidence_id","evidence","uq_evidence_location_link"),("historical_case_locations","historical_case_id","historical_cases","uq_historical_location_link"),("source_locations","source_id","web_sources","uq_source_location_link")]
    for table,record_col,record_table,uq in links:
        op.create_table(table,sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column(record_col,u,nullable=False),sa.Column("location_id",u,nullable=False),sa.Column("relationship_type",sa.String(32),server_default="REPORTED_LOCATION",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint([record_col],[f"{record_table}.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["location_id"],["locations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint(record_col,"location_id","relationship_type",name=uq))
        op.create_index(f"ix_{table}_{record_col}",table,[record_col]);op.create_index(f"ix_{table}_location_id",table,["location_id"])
    op.create_table("contradictions",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("type",sa.String(32),nullable=False),sa.Column("severity",sa.String(16),server_default="MEDIUM",nullable=False),sa.Column("description",sa.Text(),nullable=False),sa.Column("subject_type",sa.String(40),nullable=True),sa.Column("subject_id",u,nullable=True),sa.Column("source_a_type",sa.String(40),nullable=False),sa.Column("source_a_id",u,nullable=False),sa.Column("source_b_type",sa.String(40),nullable=False),sa.Column("source_b_id",u,nullable=False),sa.Column("value_a",sa.Text(),nullable=True),sa.Column("value_b",sa.Text(),nullable=True),sa.Column("date_a",sa.Date(),nullable=True),sa.Column("date_b",sa.Date(),nullable=True),sa.Column("location_a_id",u,nullable=True),sa.Column("location_b_id",u,nullable=True),sa.Column("status",sa.String(24),server_default="OPEN",nullable=False),sa.Column("investigator_note",sa.Text(),nullable=True),sa.Column("metadata",jsonb,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["location_a_id"],["locations.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["location_b_id"],["locations.id"],ondelete="SET NULL"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("investigation_id","type","source_a_type","source_a_id","source_b_type","source_b_id",name="uq_contradiction_source_pair"),sa.CheckConstraint("type IN ('DATE_CONFLICT','LOCATION_CONFLICT','ATTRIBUTE_CONFLICT','ENTITY_CONFLICT','TIMELINE_CONFLICT','SOURCE_CONFLICT')",name="ck_contradiction_type"),sa.CheckConstraint("severity IN ('LOW','MEDIUM','HIGH')",name="ck_contradiction_severity"),sa.CheckConstraint("status IN ('OPEN','REQUIRES_VERIFICATION','REVIEWED','RESOLVED','DISMISSED')",name="ck_contradiction_status"))
    op.create_index("ix_contradictions_investigation_id","contradictions",["investigation_id"])

def downgrade():
    op.drop_index("ix_contradictions_investigation_id",table_name="contradictions");op.drop_table("contradictions")
    for table,record_col in [("source_locations","source_id"),("historical_case_locations","historical_case_id"),("evidence_locations","evidence_id"),("timeline_event_locations","timeline_event_id")]:
        op.drop_index(f"ix_{table}_location_id",table_name=table);op.drop_index(f"ix_{table}_{record_col}",table_name=table);op.drop_table(table)
    op.drop_index("ix_locations_normalized_name",table_name="locations");op.drop_index("ix_locations_investigation_id",table_name="locations");op.drop_table("locations")
