"""Add structured claims, source relationships, and graph investigator artifacts."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="0011_unified_investigation_graph"
down_revision="0010_contradiction_gap_questions"
branch_labels=None
depends_on=None

def upgrade():
    u=postgresql.UUID(as_uuid=True); jsonb=postgresql.JSONB(astext_type=sa.Text())
    op.create_table("claims",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("claim_type",sa.String(24),nullable=False),sa.Column("subject",sa.String(500),nullable=False),sa.Column("predicate",sa.String(200),nullable=False),sa.Column("object_value",sa.Text(),nullable=False),sa.Column("normalized_value",sa.Text()),sa.Column("value_type",sa.String(24),nullable=False),sa.Column("date_value",sa.String(40)),sa.Column("location_text",sa.String(1000)),sa.Column("location_id",u),sa.Column("confidence_label",sa.String(16),nullable=False),sa.Column("extraction_method",sa.String(40),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_id",u,nullable=False),sa.Column("evidence_id",u),sa.Column("historical_case_id",u),sa.Column("status",sa.String(32),nullable=False),sa.Column("metadata",jsonb,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("fingerprint",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["location_id"],["locations.id"],ondelete="SET NULL"),sa.ForeignKeyConstraint(["evidence_id"],["evidence.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["historical_case_id"],["historical_cases.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("investigation_id","fingerprint",name="uq_claim_investigation_fingerprint"),sa.CheckConstraint("status IN ('SOURCE_REPORTED','AI_EXTRACTED','INVESTIGATOR_ADDED','REQUIRES_VERIFICATION')",name="ck_claim_status"),sa.CheckConstraint("claim_type IN ('DATE','TIME','LOCATION','PERSON','ORGANIZATION','VEHICLE','OBJECT','EVENT','DESCRIPTION','RELATIONSHIP','ATTRIBUTE','IDENTIFIER','OTHER')",name="ck_claim_type"))
    op.create_index("ix_claims_investigation_id","claims",["investigation_id"]);op.create_index("ix_claims_claim_type","claims",["claim_type"]);op.create_index("ix_claims_source_id","claims",["source_id"])
    op.create_table("source_relationships",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("source_a_id",u,nullable=False),sa.Column("source_b_id",u,nullable=False),sa.Column("relationship_type",sa.String(32),nullable=False),sa.Column("explanation",sa.Text(),nullable=False),sa.Column("created_by",sa.String(16),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["source_a_id"],["web_sources.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["source_b_id"],["web_sources.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"),sa.UniqueConstraint("investigation_id","source_a_id","source_b_id","relationship_type",name="uq_source_relationship_pair"),sa.CheckConstraint("relationship_type IN ('INDEPENDENT','POTENTIAL_DUPLICATE','POSSIBLE_SYNDICATION','REFERENCES','QUOTES','UNKNOWN_RELATIONSHIP')",name="ck_source_relationship_type"),sa.CheckConstraint("created_by IN ('INVESTIGATOR','SYSTEM')",name="ck_source_relationship_creator"),sa.CheckConstraint("status IN ('REQUIRES_VERIFICATION','REVIEWED','DISMISSED')",name="ck_source_relationship_status"))
    op.create_index("ix_source_relationships_investigation_id","source_relationships",["investigation_id"])
    op.create_table("graph_notes",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("node_type",sa.String(40),nullable=False),sa.Column("node_id",u,nullable=False),sa.Column("note",sa.Text(),nullable=False),sa.Column("created_by",sa.String(120),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_graph_notes_investigation_id","graph_notes",["investigation_id"])
    op.create_table("graph_bookmarks",sa.Column("id",u,server_default=sa.text("gen_random_uuid()"),nullable=False),sa.Column("investigation_id",u,nullable=False),sa.Column("name",sa.String(200),nullable=False),sa.Column("node_ids",jsonb,server_default=sa.text("'[]'::jsonb"),nullable=False),sa.Column("filters",jsonb,server_default=sa.text("'{}'::jsonb"),nullable=False),sa.Column("layout",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.ForeignKeyConstraint(["investigation_id"],["investigations.id"],ondelete="CASCADE"),sa.PrimaryKeyConstraint("id"))
    op.create_index("ix_graph_bookmarks_investigation_id","graph_bookmarks",["investigation_id"])

def downgrade():
    op.drop_table("graph_bookmarks");op.drop_table("graph_notes");op.drop_table("source_relationships");op.drop_table("claims")
