"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Plus, Pencil, Trash2, ExternalLink } from "lucide-react";
import { Shell } from "@/components/shell";
import { api } from "@/lib/api";
import type { Investigation } from "@/lib/types";

export default function InvestigationsPage(){const [items,setItems]=useState<Investigation[]|null>(null);const [error,setError]=useState("");const reload=useCallback(()=>api.investigations().then(setItems).catch((e:Error)=>setError(e.message)),[]);useEffect(()=>{reload()},[reload]);async function remove(id:string){if(!window.confirm("Delete this investigation? This action cannot be undone."))return;try{await api.delete(`/investigations/${id}`);await reload()}catch(e){setError((e as Error).message)}}return <Shell><header className="topbar"><div><span className="eyebrow">CASEWORK</span><h1>Investigations</h1></div><Link className="button" href="/investigations/new"><Plus size={16}/> New investigation</Link></header>{error&&<p className="error">{error}</p>}{items===null&&!error&&<p className="hint">Loading investigations...</p>}{items&&items.length===0&&<div className="empty"><h4>No investigations yet</h4><p>Create your first investigation to begin.</p><Link className="button" href="/investigations/new"><Plus size={16}/> Create investigation</Link></div>}{items&&items.length>0&&<div className="table-wrap"><table><thead><tr><th>Investigation</th><th>Status</th><th>Created</th><th>Updated</th><th>Actions</th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><small>{item.description||"No description"}</small></td><td><span className="status">{item.status}</span></td><td>{new Date(item.created_at).toLocaleDateString()}</td><td>{new Date(item.updated_at).toLocaleDateString()}</td><td className="actions"><Link href={`/investigations/${item.id}`} aria-label="Open"><ExternalLink size={16}/></Link><Link href={`/investigations/${item.id}?edit=1`} aria-label="Edit"><Pencil size={16}/></Link><button onClick={()=>remove(item.id)} aria-label="Delete"><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}</Shell>}
