"use client";
import { useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { Contradiction } from "@/lib/types";

const states=["OPEN","REQUIRES_VERIFICATION","REVIEWED","RESOLVED","DISMISSED"];
export function ContradictionsPanel({investigationId}:{investigationId:string}){
 const [items,setItems]=useState<Contradiction[]>([]),[filter,setFilter]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 const load=useCallback(async()=>{try{setItems(await api.contradictions(investigationId,filter?{status:filter}:{}));setError("")}catch(e){setError((e as Error).message)}},[investigationId,filter]);
 useEffect(()=>{void load()},[load]);
 async function detect(){setBusy(true);setError("");try{await api.detectContradictions(investigationId);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function review(item:Contradiction,status:string){setBusy(true);try{await api.reviewContradiction(item.id,status,notes[item.id]);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(item:Contradiction){setBusy(true);try{await api.deleteContradiction(item.id);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="contradictions-panel"><div className="section-head"><div><span className="eyebrow">SOURCE COMPARISON · NO WINNER SELECTED</span><h3>Contradictions <span className="evidence-count">{items.length}</span></h3></div><div className="geo-actions"><select aria-label="Filter contradictions by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{states.map(s=><option key={s}>{s}</option>)}</select><button className="button" disabled={busy} onClick={detect}>{busy?"Checking…":"Detect contradictions"}</button></div></div>
 {error&&<p className="error">{error}</p>}{items.length===0?<div className="empty"><h4>No contradictions in this view</h4><p>Run detection to compare dates, locations, and explicit source attributes.</p></div>:<div className="contradiction-list">{items.map(item=><article className="contradiction-card" key={item.id}><div className="contradiction-title"><span className="eyebrow">{item.type.replaceAll("_"," ")} · {item.severity}</span><span className={`review-state state-${item.status.toLowerCase()}`}>{item.status.replaceAll("_"," ")}</span></div><p>{item.description}</p><div className="contradiction-sources">{[item.source_a,item.source_b].map((source,i)=><div key={`${source.type}-${source.id}`}><span className="eyebrow">SOURCE {i===0?"A":"B"} · {source.type.replaceAll("_"," ")}</span><strong>{source.title||source.text||"Source record"}</strong><small>{source.date_text||"Date unknown"}{source.location?` · ${source.location}`:""}</small>{source.url&&safeUrl(source.url)&&<a href={safeUrl(source.url)!} target="_blank" rel="noreferrer">Open original source</a>}</div>)}</div><label>Investigator note<textarea rows={2} value={notes[item.id]??item.investigator_note??""} onChange={e=>setNotes(v=>({...v,[item.id]:e.target.value}))} placeholder="Record review context"/></label><div className="contradiction-actions"><label>Status<select value={item.status} onChange={e=>review(item,e.target.value)}>{states.map(s=><option key={s}>{s}</option>)}</select></label><button className="button secondary" disabled={busy} onClick={()=>review(item,item.status)}>Save note</button><button className="button danger" disabled={busy} onClick={()=>remove(item)}>Delete</button></div></article>)}</div>}</section>
}
function safeUrl(value:string){try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.href:null}catch{return null}}
