"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { GitCompareArrows, RefreshCw, ExternalLink, Trash2, Plus, ChevronDown } from "lucide-react";
import { api } from "@/lib/api";
import type { CorrelationRecord, CorrelationReviewStatus, CorrelationSummary, Evidence } from "@/lib/types";

type Filters = { correlation_type?: string; review_status?: CorrelationReviewStatus; reviewed?: boolean; evidence_id?: string; matrix_group?: string };
const kindOptions = ["", "SEMANTIC_SIMILARITY", "VISUAL_SIMILARITY", "GEOGRAPHIC_OVERLAP", "TEMPORAL_OVERLAP", "TEMPORAL_PROXIMITY", "ENTITY_OVERLAP", "SOURCE_REFERENCE", "CONTEXTUAL_RELEVANCE", "SHARED_ATTRIBUTE"];
const kindLabel: Record<string, string> = { SEMANTIC_SIMILARITY: "Semantic similarity", VISUAL_SIMILARITY: "Visual similarity", GEOGRAPHIC_OVERLAP: "Geographic overlap", TEMPORAL_OVERLAP: "Temporal overlap", TEMPORAL_PROXIMITY: "Temporal proximity", ENTITY_OVERLAP: "Entity overlap", SOURCE_REFERENCE: "Source reference", CONTEXTUAL_RELEVANCE: "Contextual relevance", SHARED_ATTRIBUTE: "Shared attribute", POTENTIAL_CONNECTION: "Potential connection" };
function safeExternalUrl(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.href : undefined; } catch { return undefined; }
}

export function CorrelationPanel({ investigationId, evidence }: { investigationId: string; evidence: Evidence[] }) {
  const [items, setItems] = useState<CorrelationRecord[]>([]); const [summary, setSummary] = useState<CorrelationSummary>({ total: 0, historical: 0, web: 0, news: 0, images: 0, evidence_matrix: {} });
  const [filter, setFilter] = useState<Filters>({}); const [offset, setOffset] = useState(0); const [filteredTotal, setFilteredTotal] = useState(0); const evidenceFilter=filter.evidence_id||""; const groupFilter=filter.matrix_group||""; const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [manual, setManual] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await api.correlations(investigationId, filter, offset); setItems(data.items); setFilteredTotal(data.total); setSummary(data.summary); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } }, [investigationId, filter, offset]);
  useEffect(() => { void load(); }, [load]);
  async function run() { setBusy(true); setError(""); setNotice(""); try { const result = await api.runCorrelations(investigationId); setNotice(result.status === "PARTIAL" ? `Partial analysis. ${result.failed_rules.length?`Failed rules: ${result.failed_rules.join(", ")}.`:"The per-run correlation cap was reached."}` : `Analysis complete: ${result.created} created, ${result.updated} updated, ${result.existing} already present.`); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function review(item: CorrelationRecord, status: CorrelationReviewStatus) { try { await api.reviewCorrelation(item.id, status); await load(); } catch (e) { setError((e as Error).message); } }
  async function remove(item: CorrelationRecord) { if (!window.confirm("Remove this correlation from the investigation?")) return; try { await api.deleteCorrelation(item.id); await load(); } catch (e) { setError((e as Error).message); } }
  const visible = items;
  const counts = (evidenceId: string, group: "historical"|"web"|"news"|"images") => summary.evidence_matrix[evidenceId]?.[group]||0;
  return <section className="correlation-panel" aria-labelledby="correlation-heading">
    <div className="section-head"><div><span className="eyebrow">RELATIONSHIP REVIEW</span><h3 id="correlation-heading">Evidence Correlations <span className="evidence-count">{summary.total}</span></h3><p className="correlation-subtitle">Correlations are research leads, not proof or investigative conclusions.</p></div><div className="correlation-actions"><button className="button secondary" onClick={() => setManual(true)}><Plus size={15}/> Add manual</button><button className="button" onClick={run} disabled={busy}>{busy?<RefreshCw size={15} className="spin"/>:<GitCompareArrows size={15}/>} {busy?"Analyzing…":"Run analysis"}</button></div></div>
    {error&&<p className="error">{error}</p>}{notice&&<p className="success">{notice}</p>}
    <div className="correlation-summary">{([["historical","Historical"],["web","Web"],["news","News"],["images","Images"]] as const).map(([key,label])=><div key={key}><span>{label} relationships</span><strong>{summary[key]}</strong></div>)}</div>
    {evidence.length>0&&<div className="correlation-matrix-wrap"><h4>Evidence relationship matrix</h4><div className="correlation-matrix"><div className="matrix-row matrix-header"><span>Evidence</span><span>Historical</span><span>Web</span><span>News</span><span>Images</span></div>{evidence.slice(0,50).map(record=><div className="matrix-row" key={record.id}><span title={record.title}>{record.title}</span>{(["historical","web","news","images"] as const).map(group=>{const count=counts(record.id,group);return <button key={group} className={count?"matrix-cell populated":"matrix-cell"} onClick={()=>{if(count){setOffset(0);const selected=evidenceFilter===record.id&&groupFilter===group;setFilter({...filter,evidence_id:selected?undefined:record.id,matrix_group:selected?undefined:group})}}} aria-label={`${record.title}: ${count} ${group} relationships`}>{count?`${count} links`:"—"}</button>})}</div>)}</div></div>}
    <div className="correlation-toolbar"><label>Relationship<select value={filter.correlation_type||""} onChange={e=>{setOffset(0);setFilter({...filter,correlation_type:e.target.value||undefined})}}>{kindOptions.map(value=><option key={value} value={value}>{value?kindLabel[value]:"All types"}</option>)}</select></label><label>Review status<select value={filter.review_status||""} onChange={e=>{setOffset(0);setFilter({...filter,review_status:(e.target.value||undefined) as CorrelationReviewStatus|undefined})}}><option value="">All statuses</option><option value="REQUIRES_VERIFICATION">Requires verification</option><option value="RELEVANT">Relevant</option><option value="NOT_RELEVANT">Not relevant</option></select></label><label>Review state<select value={filter.reviewed===undefined?"":String(filter.reviewed)} onChange={e=>{setOffset(0);setFilter({...filter,reviewed:e.target.value===""?undefined:e.target.value==="true"})}}><option value="">All review states</option><option value="false">Not reviewed</option><option value="true">Reviewed</option></select></label>{(evidenceFilter||groupFilter)&&<button className="filter active" onClick={()=>{setOffset(0);setFilter({...filter,evidence_id:undefined,matrix_group:undefined})}}>Clear matrix filter</button>}</div>
    {loading?<div className="loading-box">Loading correlations…</div>:visible.length===0?<div className="empty evidence-empty"><div className="empty-icon"><GitCompareArrows size={20}/></div><h4>{filteredTotal?"No correlations match the selected evidence":"No correlations identified from available data"}</h4><p>Run analysis after adding evidence, historical retrievals, or public research. Correlations require investigator verification.</p></div>:<div className="correlation-list">{visible.map(item=>{const resultUrl=safeExternalUrl(item.target.url);const historicalUrl=safeExternalUrl(item.target.source_url);return <article className="correlation-card" key={item.id}><div className="correlation-card-head"><div><span className="eyebrow">{item.created_by==="AI"?"AI-GENERATED":"INVESTIGATOR-ADDED"}</span><h4>{kindLabel[item.correlation_type]||item.correlation_type}</h4></div><span className="correlation-status">{item.review?.review_status?.replaceAll("_"," ")||"REQUIRES VERIFICATION"}</span></div><div className="correlation-pair"><div><span>Source · {item.source_type.replaceAll("_"," ")}</span><strong>{String(item.source.title||"Record")}</strong></div><ChevronDown size={15}/><div><span>Related · {item.target_type.replaceAll("_"," ")}</span><strong>{String(item.target.title||"Record")}</strong></div></div><p>{item.explanation}</p>{item.score!==null&&<div className="correlation-score"><span>{item.correlation_type=== "VISUAL_SIMILARITY"?"Visual similarity":"Semantic similarity"}</span><strong>{item.score.toFixed(3)}</strong>{item.confidence_label&&<small>{item.confidence_label} signal</small>}</div>}
      <details className="correlation-details"><summary>Why is this relationship shown?</summary><div><h5>Signals</h5>{item.supporting_attributes.length?item.supporting_attributes.map((signal,index)=><pre key={index}>{JSON.stringify(signal,null,2)}</pre>):<p>No separate signal breakdown was stored.</p>}<h5>Evidence basis and provenance</h5><pre>{JSON.stringify(item.evidence_basis,null,2)}</pre><p className="correlation-caveat">Similarity and overlap are relevance signals only. They do not establish identity, causation, or guilt.</p></div></details>
      <div className="correlation-card-foot"><span>{item.created_at?new Date(item.created_at).toLocaleString():""}</span><div>{(["RELEVANT","NOT_RELEVANT","REQUIRES_VERIFICATION"] as CorrelationReviewStatus[]).map(status=><button key={status} className="review-chip" onClick={()=>review(item,status)}>{status=== "NOT_RELEVANT"?"Not relevant":status.replaceAll("_"," ")}</button>)}<button className="icon-button" onClick={()=>remove(item)} aria-label="Delete correlation"><Trash2 size={15}/></button></div></div>{item.source_type==="EVIDENCE"&&<a className="correlation-link" href={`#evidence-${item.source_id}`}>Open source evidence <ExternalLink size={13}/></a>}{resultUrl&&<a className="correlation-link" href={resultUrl} target="_blank" rel="noreferrer">Open related source <ExternalLink size={13}/></a>}{historicalUrl&&<a className="correlation-link" href={historicalUrl} target="_blank" rel="noreferrer">Open historical source <ExternalLink size={13}/></a>}</article>})}</div>}
    {filteredTotal>500&&<div className="correlation-pagination"><span>{offset+1}–{Math.min(offset+items.length,filteredTotal)} of {filteredTotal}</span><button className="button secondary" disabled={offset===0} onClick={()=>setOffset(Math.max(0,offset-500))}>Previous</button><button className="button secondary" disabled={offset+500>=filteredTotal} onClick={()=>setOffset(offset+500)}>Next</button></div>}
    {manual&&<ManualForm investigationId={investigationId} evidence={evidence} onClose={()=>setManual(false)} onCreated={async()=>{setManual(false);setNotice("Investigator-added relationship saved.");await load()}} onError={setError}/>}
  </section>;
}

function ManualForm({investigationId,evidence,onClose,onCreated,onError}:{investigationId:string;evidence:Evidence[];onClose:()=>void;onCreated:()=>Promise<void>;onError:(message:string)=>void}) {
  const [source,setSource]=useState(evidence[0]?.id||"");const [targetType,setTargetType]=useState("HISTORICAL_CASE");const [target,setTarget]=useState("");const [note,setNote]=useState("");const [busy,setBusy]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);try{await api.createManualCorrelation(investigationId,{source_type:"EVIDENCE",source_id:source,target_type:targetType,target_id:target,correlation_type:"POTENTIAL_CONNECTION",note});await onCreated()}catch(e){onError((e as Error).message)}finally{setBusy(false)}}
  return <div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="dialog" role="dialog" aria-modal="true"><header className="dialog-head"><div><span className="eyebrow">INVESTIGATOR-ADDED</span><h2>Add a manual relationship</h2></div><button className="icon-button" onClick={onClose}>×</button></header><form className="evidence-form" onSubmit={submit}><label>Evidence<select required value={source} onChange={e=>setSource(e.target.value)}>{evidence.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Related record type<select value={targetType} onChange={e=>setTargetType(e.target.value)}>{["HISTORICAL_CASE","HISTORICAL_IMAGE","WEB_RESULT","NEWS_RESULT","IMAGE_RESULT","SOURCE"].map(x=><option key={x}>{x}</option>)}</select></label><label>Related record UUID<input required value={target} onChange={e=>setTarget(e.target.value)} placeholder="Paste the record ID"/></label><label>Investigator note<textarea required maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Why should these records be reviewed together?"/></label><p className="hint">This relationship will be labeled Investigator-added and will not be treated as an AI finding.</p><div className="form-actions"><button type="button" className="button secondary" onClick={onClose}>Cancel</button><button className="button" disabled={busy||!source||!target||!note.trim()}>{busy?"Saving…":"Save relationship"}</button></div></form></section></div>;
}
