"use client";
import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import type { GeoLocation, GeoSummary } from "@/lib/types";

const LeafletMap=dynamic(()=>import("./leaflet-map"),{ssr:false,loading:()=> <div className="loading-box">Loading map…</div>});
const layerTypes=["EVIDENCE","TIMELINE_EVENT","HISTORICAL_CASE","WEB_SOURCE","NEWS_SOURCE","INVESTIGATOR"];
const heatModes=["ALL_RECORDS","EVIDENCE","TIMELINE_EVENTS","HISTORICAL_CASES","WEB_SOURCES","NEWS_SOURCES","CORRELATIONS"];
export function GeospatialPanel({investigationId}:{investigationId:string}){
 const [locations,setLocations]=useState<GeoLocation[]>([]),[summary,setSummary]=useState<GeoSummary|null>(null),[heat,setHeat]=useState<{points:Array<{latitude:number;longitude:number;weight:number}>;correlations:Array<{id:string;coordinates:[[number,number],[number,number]];source_location:string;target_location:string;explanation:string;score:number|null}>}|null>(null),[selected,setSelected]=useState<GeoLocation|null>(null),[mode,setMode]=useState("ALL_RECORDS"),[layers,setLayers]=useState<string[]>(layerTypes),[heatmap,setHeatmap]=useState(false),[from,setFrom]=useState(""),[to,setTo]=useState(""),[precision,setPrecision]=useState(""),[conflict,setConflict]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{setError("");try{const filters:Record<string,string>={};if(from)filters.date_from=from;if(to)filters.date_to=to;if(precision)filters.precision=precision;if(conflict)filters.conflict_only="true";const [loc,sum,hm]=await Promise.all([api.geospatialLocations(investigationId,filters),api.geospatialSummary(investigationId),api.geospatialHeatmap(investigationId,{...filters,mode})]);setLocations(loc);setSummary(sum);setHeat(hm)}catch(e){setError((e as Error).message)}},[investigationId,from,to,precision,conflict,mode]);
 useEffect(()=>{void load()},[load]);
 const visible=useMemo(()=>locations.map(l=>({...l,records:l.records.filter(r=>layers.includes(r.source_type))})).filter(l=>l.records.length||(!l.latitude&&layers.includes("INVESTIGATOR"))),[locations,layers]);
 async function run(action:"rebuild"|"geocode"){setBusy(true);setError("");try{if(action==="rebuild")await api.rebuildGeospatial(investigationId);else await api.geocodeLocations(investigationId);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="geo-panel"><div className="section-head"><div><span className="eyebrow">PHASE 9 · LOCATION INTELLIGENCE</span><h3>Investigation map</h3></div><div className="geo-actions"><button className="button secondary" disabled={busy} onClick={()=>run("rebuild")}>{busy?"Working…":"Rebuild location links"}</button><button className="button" disabled={busy} onClick={()=>run("geocode")}>Geocode queued locations</button></div></div>
 {summary&&<div className="geo-stat-grid">{[["Mapped records",summary.mapped_records],["Unmapped records",summary.unmapped_records],["Locations",summary.unique_locations],["Approximate locations",summary.approximate_locations],["Open contradictions",summary.open_contradictions]].map(([label,value])=><div className="geo-stat" key={label}><span>{label}</span><strong>{value}</strong></div>)}</div>}
 {error&&<p className="error">{error}</p>}<div className="geo-controls"><label>Heatmap mode<select value={mode} onChange={e=>setMode(e.target.value)}>{heatModes.map(x=><option key={x}>{x}</option>)}</select></label><label>From<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>To<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Precision<select value={precision} onChange={e=>setPrecision(e.target.value)}><option value="">All precision</option>{["EXACT_POINT","STREET","NEIGHBORHOOD","LOCALITY","CITY","DISTRICT","STATE","COUNTRY","REGION","APPROXIMATE","UNKNOWN"].map(x=><option key={x}>{x}</option>)}</select></label><label className="geo-check"><input type="checkbox" checked={conflict} onChange={e=>setConflict(e.target.checked)}/> Conflicts only</label><label className="geo-check"><input type="checkbox" checked={heatmap} onChange={e=>setHeatmap(e.target.checked)}/> Show density heatmap</label></div>
 <div className="geo-layers"><strong>Visible source layers</strong>{layerTypes.map(x=><label key={x}><input type="checkbox" checked={layers.includes(x)} onChange={e=>setLayers(v=>e.target.checked?[...v,x]:v.filter(y=>y!==x))}/>{x.replaceAll("_"," ")}</label>)}</div>
 <p className="geo-method">Each source-backed record contributes weight 1. Density shows mapped record counts only; it does not represent crime or risk probability. Approximate locations are drawn as dashed areas.</p>
 <div className="geo-map-layout"><LeafletMap locations={visible} heatmap={heatmap} heatPoints={(heat?.points||[]).map(p=>[p.latitude,p.longitude,p.weight])} correlations={heat?.correlations||[]} onSelect={setSelected}/><aside className="geo-provenance"><h4>{selected?.raw_text||"Location provenance"}</h4>{selected?<><p>{selected.normalized_name} · {selected.precision}</p><p>{selected.geocoding_status} · {selected.geocoding_source||"No geocoding source"}</p>{selected.records.map(r=><article className="geo-record" key={`${r.source_type}-${r.source_id}`}><span className="eyebrow">{r.source_type.replaceAll("_"," ")} · {r.relationship_type}</span><strong>{r.title||"Untitled record"}</strong><small>{r.date_start||"Date unknown"}{r.source_name?` · ${r.source_name}`:""}</small>{r.url&&safeUrl(r.url)&&<a href={safeUrl(r.url)!} target="_blank" rel="noreferrer">Open source</a>}{r.source_type==="EVIDENCE"&&<a href={`#evidence-${r.source_id}`}>Open evidence</a>}</article>)}{selected.conflicts.map(c=><article className="geo-conflict" key={c.id}>⚠ {c.type}: {c.description}</article>)}</>:<p>Select a mapped location to inspect its source records and provenance.</p>}</aside></div></section>
}
function safeUrl(value:string){try{const url=new URL(value);return ["http:","https:"].includes(url.protocol)?url.href:null}catch{return null}}
