"use client";
import { useCallback, useEffect, useState } from "react";
import { Search, ExternalLink, X } from "lucide-react";
import { api } from "@/lib/api";
import type { Evidence, EvidenceHistoricalSearchResult, HistoricalCaseDetail, HistoricalIndexStatus, HistoricalSearchResult } from "@/lib/types";

function safeWebUrl(value: string | null): string | null {
  if (!value) return null;
  try { const url = new URL(value); return url.protocol === "https:" || url.protocol === "http:" ? url.href : null; } catch { return null; }
}

export function HistoricalPanel({ investigationId, refreshKey = 0 }: { investigationId: string; refreshKey?: number }) {
  const [items,setItems]=useState<Evidence[]|null>(null);const [error,setError]=useState("");const [selected,setSelected]=useState<string[]>([]);const [topK,setTopK]=useState(10);const [result,setResult]=useState<EvidenceHistoricalSearchResult|null>(null);const [busy,setBusy]=useState(false);const [caseDetail,setCaseDetail]=useState<HistoricalCaseDetail|null>(null);const [detailResult,setDetailResult]=useState<HistoricalSearchResult|null>(null);const [detailLoading,setDetailLoading]=useState(false);const [index,setIndex]=useState<HistoricalIndexStatus|null>(null);
  const load=useCallback(()=>{setItems(null);api.evidence(investigationId,{type:"TEXT"}).then(data=>{setItems(data);setSelected(prev=>prev.filter(id=>data.some(item=>item.id===id))) }).catch((e:Error)=>setError(e.message))},[investigationId]);
  useEffect(()=>{load()},[load,refreshKey]);
  useEffect(()=>{let active=true;api.historicalIndexStatus().then(value=>{if(active)setIndex(value)}).catch(()=>{if(active)setIndex(null)});return()=>{active=false}},[refreshKey]);
  async function run(){setError("");setBusy(true);try{setResult(await api.searchInvestigationHistorical(investigationId,selected,topK))}catch(e){setError((e as Error).message);setResult(null)}finally{setBusy(false)}}
  async function openCase(record:HistoricalSearchResult){setDetailResult(record);setCaseDetail({historical_case_id:record.historical_case_id,external_id:null,title:record.title,summary:record.summary,description:record.description,date:record.date,location:record.location,case_type:record.case_type,status:record.status,source:record.source});setDetailLoading(true);try{setCaseDetail(await api.historicalCase(record.historical_case_id))}catch(e){setError((e as Error).message)}finally{setDetailLoading(false)}}
  const traces=result?.query_source.filter(source=>source.evidence_id)||[];
  return <section className="historical-section"><div className="section-head"><div><span className="eyebrow">RETRIEVAL WORKSPACE</span><h3>Historical Matches</h3></div></div><div className="historical-panel"><div className="historical-toolbar"><div><strong>Historical case retrieval</strong><p>Search the historical knowledge base using selected text evidence.</p></div><label>Results<select value={topK} onChange={e=>setTopK(Number(e.target.value))}>{[5,10,20].map(value=><option key={value} value={value}>{value}</option>)}</select></label></div>
      <div className={`index-state ${index?.status === "READY" ? "ready" : "degraded"}`}><span className="index-dot"/><span>{index ? `Knowledge base ${index.status.toLowerCase().replaceAll("_", " ")} · ${index.historical_case_count.toLocaleString()} cases · ${index.embedding_model}` : "Knowledge base status unavailable"}</span></div>
      {error&&<p className="error">{error}</p>}{items===null&&!error&&<p className="hint">Loading text evidence…</p>}{items?.length===0&&<p className="hint">Add text evidence to search the historical knowledge base. Image and document analysis is not available in this phase.</p>}
      {items&&items.length>0&&<div className="evidence-picker">{items.map(item=><label key={item.id} className="evidence-check"><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>{setSelected(current=>e.target.checked?[...current,item.id]:current.filter(id=>id!==item.id));setResult(null)}}/><span><strong>{item.title}</strong><small>{item.text_content?.slice(0,150)||"No searchable text"}</small></span></label>)}</div>}
      <div className="historical-run"><span>{selected.length} evidence item{selected.length===1?"":"s"} selected</span><button className="button" disabled={busy||selected.length===0||index?.status!=="READY"} onClick={run}><Search size={15}/>{busy?"Searching…":"Search Historical Cases"}</button></div>
      {index&&index.status!=="READY"&&<p className="index-message">Historical search is disabled until the case dataset and vector index are ready.</p>}
      {busy&&<div className="loading-box historical-loading"><span>Searching historical case knowledge base…</span><span>Generating semantic representation…</span><span>Retrieving potentially relevant records…</span></div>}
      {result&&<div className="historical-results"><div className="retrieval-note"><strong>Potentially Relevant Historical Cases</strong><span>Model: {result.model} · Semantic similarity is a retrieval signal and requires verification.</span><small>Query source: {traces.map(t=>t.title).join(", ")||"Selected evidence"}</small></div>{result.results.length===0?<div className="no-results"><strong>No sufficiently relevant historical cases were retrieved.</strong><p>Try adding more descriptive evidence, selecting additional evidence, adjusting the search, or reviewing historical dataset coverage.</p></div>:result.results.map(record=><article className="historical-result" key={record.historical_case_id}><div className="historical-result-main"><span className="eyebrow">RESEARCH LEAD · REQUIRES VERIFICATION</span><h4>{record.title}</h4><div className="historical-meta">{[record.location,record.date,record.case_type].filter(Boolean).join(" · ")||"No additional case details in source record"}</div><p>{record.summary||record.description||"The source record contains no summary."}</p>{safeWebUrl(record.source.url)&&<a href={safeWebUrl(record.source.url)!} target="_blank" rel="noreferrer" className="source-link">{record.source.name||"Source Record"}<ExternalLink size={12}/></a>}</div><div className="similarity"><span>SEMANTIC SIMILARITY</span><strong>{record.similarity_score.toFixed(3)}</strong><button className="text-link" onClick={()=>openCase(record)}>View case</button></div></article>)}</div>}
    </div>{caseDetail&&<div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setCaseDetail(null)}}><section className="dialog detail-dialog" role="dialog" aria-modal="true"><header className="dialog-head"><div><span className="eyebrow">HISTORICAL CASE · SOURCE RECORD</span><h2>{caseDetail.title}</h2></div><button className="icon-button" onClick={()=>setCaseDetail(null)} aria-label="Close"><X size={18}/></button></header><div className="case-detail-grid">{[["DATE",caseDetail.date],["LOCATION",caseDetail.location],["CASE TYPE",caseDetail.case_type],["STATUS",caseDetail.status],["SOURCE",caseDetail.source.name],["SEMANTIC SIMILARITY",detailResult?.similarity_score.toFixed(3)||null]].filter(([,value])=>value).map(([label,value])=><div key={label}><span className="eyebrow">{label}</span><p>{value}</p></div>)}</div>{caseDetail.summary&&<div className="case-prose"><span className="eyebrow">SUMMARY</span><p>{caseDetail.summary}</p></div>}{caseDetail.description&&<div className="case-prose"><span className="eyebrow">DESCRIPTION</span><p>{caseDetail.description}</p></div>}<div className="retrieved-because"><span className="eyebrow">RETRIEVED BECAUSE</span><p>{traces.map(trace=>trace.title).join(", ")||"Search evidence"}</p><small>Retrieved from the historical knowledge base using {result?.model}. Semantic similarity does not establish a factual connection.</small></div>{safeWebUrl(caseDetail.source.url)&&<a className="button secondary download" href={safeWebUrl(caseDetail.source.url)!} target="_blank" rel="noreferrer">Open source record <ExternalLink size={14}/></a>}{detailLoading&&<p className="hint">Loading historical case…</p>}</section></div>}</section>
}
