"use client";
import { useEffect } from "react";
import L from "leaflet";
import "leaflet.heat";
import { CircleMarker, MapContainer, Marker, Polyline, Popup, TileLayer, useMap } from "react-leaflet";
import MarkerClusterGroup from "react-leaflet-cluster";
import type { GeoLocation } from "@/lib/types";

type CorrelationLine={id:string;coordinates:[[number,number],[number,number]];source_location:string;target_location:string;explanation:string;score:number|null};
function FitLocations({locations}:{locations:GeoLocation[]}){const map=useMap();useEffect(()=>{const pts=locations.filter(x=>x.latitude!==null&&x.longitude!==null).map(x=>[x.latitude!,x.longitude!] as [number,number]);if(pts.length===1)map.setView(pts[0],Math.max(map.getZoom(),8));else if(pts.length>1)map.fitBounds(L.latLngBounds(pts).pad(.15),{maxZoom:11});},[locations,map]);return null;}
function HeatLayer({points,enabled}:{points:Array<[number,number,number]>;enabled:boolean}){const map=useMap();useEffect(()=>{if(!enabled||points.length<2)return;const layer=L.heatLayer(points,{radius:28,blur:22,maxZoom:12,minOpacity:.22});layer.addTo(map);return()=>{map.removeLayer(layer)};},[enabled,map,points]);return null;}
const pointIcon=L.divIcon({className:"geo-marker-wrap",html:'<span class="geo-marker-point" aria-hidden="true"></span>',iconSize:[18,18],iconAnchor:[9,9]});
function itemLabel(loc:GeoLocation){return `${loc.raw_text} · ${loc.precision}${loc.precision==="APPROXIMATE"?" · Approximate":""}`;}
export default function LeafletMap({locations,heatmap,heatPoints,correlations,gapLocationIds=[],showConflicts=true,onSelect}:{locations:GeoLocation[];heatmap:boolean;heatPoints:Array<[number,number,number]>;correlations:CorrelationLine[];gapLocationIds?:string[];showConflicts?:boolean;onSelect:(location:GeoLocation)=>void}){
 return <div className="leaflet-map-shell"><MapContainer center={[20.5,78.9]} zoom={4} minZoom={2} maxZoom={18} scrollWheelZoom className="leaflet-map"><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap contributors</a>' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><FitLocations locations={locations}/><HeatLayer points={heatPoints} enabled={heatmap}/>
   <MarkerClusterGroup chunkedLoading showCoverageOnHover={false}>{locations.filter(x=>x.latitude!==null&&x.longitude!==null&&x.precision!=="APPROXIMATE").map(loc=><Marker key={loc.id} position={[loc.latitude!,loc.longitude!]} icon={pointIcon} eventHandlers={{click:()=>onSelect(loc)}}><Popup><strong>{itemLabel(loc)}</strong><p>{loc.records.length} mapped record{loc.records.length===1?"":"s"}</p>{loc.conflicts.length>0&&<b className="map-conflict-label">⚠ Location conflict</b>}{loc.records.slice(0,8).map(r=><div key={`${r.source_type}-${r.source_id}`}><b>{r.source_type.replaceAll("_"," ")}</b> · {r.title||"Untitled record"}</div>)}</Popup></Marker>)}</MarkerClusterGroup>
   {locations.filter(x=>x.latitude!==null&&x.longitude!==null&&x.precision==="APPROXIMATE").map(loc=><CircleMarker key={loc.id} center={[loc.latitude!,loc.longitude!]} radius={15} pathOptions={{color:"#f59e0b",weight:2,dashArray:"4 4",fillColor:"#fbbf24",fillOpacity:.18}} eventHandlers={{click:()=>onSelect(loc)}}><Popup><strong>{itemLabel(loc)}</strong><p>Approximate area marker, not an exact point.</p>{loc.records.slice(0,8).map(r=><div key={`${r.source_type}-${r.source_id}`}>{r.source_type.replaceAll("_"," ")} · {r.title||"Untitled record"}</div>)}</Popup></CircleMarker>)}
   {showConflicts&&locations.filter(x=>x.conflicts.length>0&&x.latitude!==null&&x.longitude!==null).map(loc=><CircleMarker key={`conflict-${loc.id}`} center={[loc.latitude!,loc.longitude!]} radius={22} pathOptions={{color:"#dc2626",weight:2,dashArray:"3 5",fillOpacity:0}}><Popup><strong>Reported location conflict · verification needed</strong>{loc.conflicts.map(c=><p key={c.id}>{c.description}</p>)}</Popup></CircleMarker>)}
   {locations.filter(x=>gapLocationIds.includes(x.id)&&x.latitude!==null&&x.longitude!==null).map(loc=><CircleMarker key={`gap-${loc.id}`} center={[loc.latitude!,loc.longitude!]} radius={25} pathOptions={{color:"#7c3aed",weight:2,dashArray:"2 5",fillOpacity:0}}><Popup><strong>Research gap linked to this documented location</strong><p>{loc.raw_text} · {loc.precision}</p></Popup></CircleMarker>)}
   {correlations.map(c=><Polyline key={c.id} positions={c.coordinates} pathOptions={{color:"#a855f7",weight:2,dashArray:"5 7",opacity:.65}}><Popup><strong>Geographic overlap</strong><p>{c.source_location} ↔ {c.target_location}</p><p>Existing correlation; overlap is not proof of a relationship.</p><small>{c.explanation}</small></Popup></Polyline>)}
 </MapContainer></div>;
}
