"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { InvestigationQuestion, ResearchGap, ResearchGapSummary, TimelineEvent } from "@/lib/types";

const gapStatuses=["OPEN","RESEARCHING","SUFFICIENTLY_ADDRESSED","DISMISSED"];
const questionStatuses=["OPEN","RESEARCHING","PARTIALLY_ADDRESSED","ANSWERED","DISMISSED"];
export function ResearchHealthPanel({investigationId,evidenceCount}:{investigationId:string;evidenceCount:number}){
 const [data,setData]=useState<{timeline:TimelineEvent[];locations:number;unmapped:number;contradictions:number;openContradictions:number;gaps:number;openGaps:number;sources:number;sourceTypes:Record<string,number>}|null>(null);
 const [error,setError]=useState("");useEffect(()=>{let active=true;Promise.all([api.timeline(investigationId),api.geospatialSummary(investigationId),api.contradictionSummary(investigationId),api.researchGapSummary(investigationId),api.researchSources(investigationId)]).then(([timeline,geo,conflicts,gaps,sources])=>{if(!active)return;const sourceTypes:Record<string,number>={};for(const item of sources.items)sourceTypes[item.source_type]=(sourceTypes[item.source_type]||0)+1;setData({timeline,locations:geo.mapped_records,unmapped:geo.unmapped_records,contradictions:conflicts.total,openContradictions:(conflicts.statuses.OPEN||0)+(conflicts.statuses.UNDER_REVIEW||0)+(conflicts.statuses.REQUIRES_VERIFICATION||0),gaps:gaps.total,openGaps:gaps.open,sources:sources.total,sourceTypes})}).catch(e=>active&&setError((e as Error).message));return()=>{active=false}},[investigationId]);
 const events=data?.timeline||[],denom=Math.max(events.length,1),dateCoverage=Math.round(events.filter(e=>e.date_start).length/denom*100),eventSources=Math.round(events.filter(e=>e.sources?.length||e.source_id).length/denom*100),geoDenom=data?Math.max(data.locations+data.unmapped,1):1;
 return <section className="research-health"><header><div><span className="eyebrow">RESEARCH HEALTH · RECORD COVERAGE ONLY</span><h3>Coverage overview</h3></div><span className="coverage-note">Coverage measures describe available records; they are not case strength or truth estimates.</span></header>{error&&<p className="error">{error}</p>}{!data?<p className="hint">Loading research coverage…</p>:<><div className="health-counts">{[["Evidence records",evidenceCount],["Web sources",data.sources],["Timeline events",events.length],["Mapped records",data.locations],["Open contradictions",data.openContradictions],["Open research gaps",data.openGaps]].map(([label,count])=><div key={label}><span>{label}</span><strong>{count}</strong></div>)}</div><div className="coverage-bars">{[["Timeline dates",dateCoverage,"Share of stored timeline events with a normalized event date."],["Timeline source links",eventSources,"Share of stored timeline events with at least one source link."],["Geographic coverage",Math.round(data.locations/geoDenom*100),"Mapped records divided by mapped and unmapped record counts."]].map(([label,value,description])=><div title={String(description)} key={String(label)}><span>{label}<small>{description}</small></span><div className="coverage-track"><i style={{width:`${value}%`}}/></div><b>{value}%</b></div>)}</div><div className="source-diversity"><span className="eyebrow">STORED SOURCES BY TYPE · NOT A RELIABILITY RANKING</span>{Object.entries(data.sourceTypes).map(([kind,count])=><span key={kind}>{kind.replaceAll("_"," ")} <b>{count}</b></span>)}</div></>}</section>
}
export function ResearchGapsPanel({investigationId}:{investigationId:string}){
 const [items,setItems]=useState<ResearchGap[]>([]),[summary,setSummary]=useState<ResearchGapSummary|null>(null),[filter,setFilter]=useState(""),[typeFilter,setTypeFilter]=useState(""),[priorityFilter,setPriorityFilter]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const filters:Record<string,string>={};if(filter)filters.status=filter;if(typeFilter)filters.type=typeFilter;if(priorityFilter)filters.priority=priorityFilter;const [rows,count]=await Promise.all([api.researchGaps(investigationId,filters),api.researchGapSummary(investigationId)]);setItems(rows);setSummary(count);setError("")}catch(e){setError((e as Error).message)}},[investigationId,filter,typeFilter,priorityFilter]);useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("coldsync:research-refresh",refresh);return()=>window.removeEventListener("coldsync:research-refresh",refresh)},[load]);
 useEffect(()=>{if(!items.some(x=>x.status==="RESEARCHING"))return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[items,load]);
 async function detect(){setBusy(true);try{await api.detectGaps(investigationId);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function update(gap:ResearchGap,status:string){setBusy(true);try{await api.updateGap(gap.id,{status});await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function research(gap:ResearchGap){setBusy(true);try{await api.researchGap(gap.id);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="research-panel" id="research-gaps"><header className="section-head"><div><span className="eyebrow">RESEARCH INTELLIGENCE · COVERAGE NEEDS</span><h3>Research gaps <span className="evidence-count">{summary?.open??"—"} open</span></h3></div><div className="geo-actions"><select aria-label="Filter gaps by status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="">All statuses</option>{gapStatuses.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter gaps by type" value={typeFilter} onChange={e=>setTypeFilter(e.target.value)}><option value="">All gap types</option>{["MISSING_DATE","MISSING_LOCATION","MISSING_SOURCE","INSUFFICIENT_SOURCE_COVERAGE","CONTRADICTORY_INFORMATION","UNRESOLVED_TIMELINE","UNRESOLVED_LOCATION","UNDER_RESEARCHED_ENTITY","UNDER_RESEARCHED_LOCATION","MISSING_HISTORICAL_CONTEXT","UNANSWERED_QUESTION"].map(x=><option key={x}>{x}</option>)}</select><select aria-label="Filter gaps by priority" value={priorityFilter} onChange={e=>setPriorityFilter(e.target.value)}><option value="">All priorities</option>{["HIGH","MEDIUM","LOW"].map(x=><option key={x}>{x}</option>)}</select><button className="button" onClick={detect} disabled={busy}>{busy?"Working…":"Re-run gap detection"}</button></div></header>
 {summary&&<div className="geo-stat-grid gap-stats">{[["Open",summary.open],["High priority",summary.high_priority],["Researching",summary.researching],["Addressed",summary.addressed],["Dismissed",summary.dismissed]].map(([name,n])=><div className="geo-stat" key={name}><span>{name}</span><strong>{n}</strong></div>)}</div>}
 {error&&<p className="error">{error}</p>}{items.length===0?<div className="empty"><h4>No research gaps in this view</h4><p>Detection uses currently stored evidence, timeline, source, location, correlation, and contradiction records.</p></div>:<div className="gap-list">{items.map(g=><GapCard key={g.id} gap={g} busy={busy} onStatus={s=>update(g,s)} onResearch={()=>research(g)}/>)}</div>}</section>
}
function GapCard({gap,busy,onStatus,onResearch}:{gap:ResearchGap;busy:boolean;onStatus:(s:string)=>void;onResearch:()=>void}){
 return <article className="gap-card"><header className="gap-card-head"><div><span className="eyebrow">{gap.gap_type.replaceAll("_"," ")} · {gap.priority} PRIORITY</span><h4>{gap.title}</h4></div><span className={`review-state state-${gap.status.toLowerCase()}`}>{gap.status.replaceAll("_"," ")}</span></header><p>{gap.description}</p><div className="gap-basis"><strong>Why this was identified</strong><span>Based on linked investigation records; this is a coverage signal and does not establish that an event occurred.</span></div>{gap.suggested_research_actions.length>0&&<div className="suggested-actions"><strong>Suggested next actions</strong>{gap.suggested_research_actions.map((a,i)=><span key={i}><b>{a.tool.replaceAll("_"," ")}</b>{a.query_template&&<> · <code>{a.query_template}</code></>} — {a.reason}</span>)}</div>}
 <div className="gap-links">{gap.related_timeline_event_ids.map(id=><a key={id} href={`#timeline-event-${id}`}>View timeline event</a>)}{gap.related_evidence_ids.map(id=><a key={id} href={`#evidence-${id}`}>View evidence</a>)}{gap.related_location_ids.length>0&&<a href="#geospatial-intelligence">View map locations</a>}{gap.related_contradiction_ids.map(id=><a key={id} href={`#contradiction-${id}`}>View contradiction</a>)}</div>
 <div className="gap-actions"><label>Status<select value={gap.status} onChange={e=>onStatus(e.target.value)} disabled={busy}>{gapStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="button" disabled={busy||gap.status==="DISMISSED"||gap.status==="RESEARCHING"} onClick={onResearch}>{gap.status==="RESEARCHING"?"Research queued":"Research this gap"}</button></div></article>
}

export function QuestionsPanel({investigationId}:{investigationId:string}){
 const [items,setItems]=useState<InvestigationQuestion[]>([]),[gaps,setGaps]=useState<ResearchGap[]>([]),[question,setQuestion]=useState(""),[selectedGaps,setSelectedGaps]=useState<string[]>([]),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const load=useCallback(async()=>{try{const [q,g]=await Promise.all([api.questions(investigationId,status?{status}:{}),api.researchGaps(investigationId)]);setItems(q);setGaps(g);setError("")}catch(e){setError((e as Error).message)}},[investigationId,status]);useEffect(()=>{void load()},[load]);useEffect(()=>{if(!items.some(x=>x.status==="RESEARCHING"))return;const timer=window.setInterval(()=>void load(),3000);return()=>window.clearInterval(timer)},[items,load]);
 async function add(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createQuestion(investigationId,{question,related_gap_ids:selectedGaps});setQuestion("");setSelectedGaps([]);await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function change(item:InvestigationQuestion,next:string){setBusy(true);try{await api.updateQuestion(item.id,{status:next});await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 async function research(item:InvestigationQuestion){setBusy(true);try{await api.researchQuestion(item.id);await load()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 return <section className="research-panel" id="research-questions"><header className="section-head"><div><span className="eyebrow">INVESTIGATOR-DEFINED</span><h3>Research questions</h3></div><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">All statuses</option>{questionStatuses.map(s=><option key={s}>{s}</option>)}</select></header>{error&&<p className="error">{error}</p>}<form className="question-create" onSubmit={add}><label>Investigation question<input required minLength={5} maxLength={1000} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What information should be checked in available records?"/></label>{gaps.length>0&&<label>Connect research gaps<select multiple value={selectedGaps} onChange={e=>setSelectedGaps(Array.from(e.target.selectedOptions,x=>x.value))}>{gaps.map(g=><option key={g.id} value={g.id}>{g.gap_type.replaceAll("_"," ")} · {g.title}</option>)}</select></label>}<button className="button" disabled={busy||question.trim().length<5}>Add question</button></form>{items.length===0?<div className="empty"><h4>No research questions yet</h4><p>Add a question to keep an investigator-defined research task connected to records and gaps.</p></div>:<div className="question-list">{items.map(item=><article className="question-card" key={item.id}><div><span className="eyebrow">{item.priority} PRIORITY · {item.related_gap_ids.length} LINKED GAP{item.related_gap_ids.length===1?"":"S"}</span><h4>{item.question}</h4><small>Research results inform investigator review; “Answered” does not assert objective truth.</small>{item.related_gap_ids.map(id=>{const gap=gaps.find(x=>x.id===id);return gap?<a className="question-gap-link" key={id} href="#research-gaps">↳ {gap.title}</a>:null})}</div><div className="gap-actions"><label>Status<select value={item.status} onChange={e=>change(item,e.target.value)} disabled={busy}>{questionStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button className="button" disabled={busy||item.status==="DISMISSED"||item.status==="RESEARCHING"} onClick={()=>research(item)}>{item.status==="RESEARCHING"?"Research queued":"Research question"}</button></div></article>)}</div>}</section>
}
