"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { CalendarClock, Plus, RefreshCw, Search, AlertTriangle, Trash2 } from "lucide-react";
import { api } from "@/lib/api";
import type { TimelineEvent, Contradiction } from "@/lib/types";

const sourceFilters=["ALL","EVIDENCE","HISTORICAL_CASE","WEB_RESULT","NEWS_RESULT","IMAGE_RESULT","INVESTIGATOR"];
const sourceNames:Record<string,string>={EVIDENCE:"Evidence",HISTORICAL_CASE:"Historical",WEB_RESULT:"Web",NEWS_RESULT:"News",IMAGE_RESULT:"Image",SOURCE:"Source",INVESTIGATOR:"Investigator"};
const sourceLabel=(s:string|null)=>sourceNames[s||""]||"Source";
function displayDate(e:TimelineEvent){if(!e.date_start)return "Date unavailable";if(e.date_precision==="YEAR")return e.date_start.slice(0,4);if(e.date_precision==="MONTH")return new Date(`${e.date_start}T00:00:00Z`).toLocaleDateString("en",{month:"long",year:"numeric",timeZone:"UTC"});if(e.date_precision==="APPROXIMATE"||e.date_precision==="RANGE")return e.date_text||`${e.date_start} – ${e.date_end}`;return new Date(`${e.date_start}T00:00:00Z`).toLocaleDateString("en",{year:"numeric",month:"long",day:"numeric",timeZone:"UTC"});}
export function TimelinePanel({investigationId}:{investigationId:string}){
 const [events,setEvents]=useState<TimelineEvent[]|null>(null),[issues,setIssues]=useState<Contradiction[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[source,setSource]=useState("ALL"),[review,setReview]=useState("ALL"),[query,setQuery]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState(""),[selected,setSelected]=useState<TimelineEvent|null>(null),[manual,setManual]=useState(false),[editing,setEditing]=useState<TimelineEvent|null>(null);
 const load=useCallback(()=>{setError("");const f:Record<string,string>={};if(source!=="ALL")f.source_type=source;if(review==="REVIEW")f.status="AI_EXTRACTED";if(review==="DISMISSED")f.status="DISMISSED";if(dateFrom)f.date_from=dateFrom;if(dateTo)f.date_to=dateTo;if(query.trim())f.q=query.trim();Promise.all([api.timeline(investigationId,f),api.contradictions(investigationId)]).then(([rows,conflicts])=>{setEvents(rows);setIssues(conflicts)}).catch((e:Error)=>{setEvents([]);setIssues([]);setError(e.message)})},[investigationId,source,review,dateFrom,dateTo,query]);
 useEffect(()=>{load()},[load]);
 async function generate(){setBusy(true);setError("");setNotice("");try{const r=await api.generateTimeline(investigationId);setEvents(r.events);setNotice(r.partial_sources.length?`Timeline ready with unavailable sources: ${r.partial_sources.join(", ")}`:`Timeline updated · ${r.created} new events`)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remove(e:TimelineEvent){if(!window.confirm(`Delete timeline event “${e.title}”?`))return;try{await api.deleteTimelineEvent(e.id);setSelected(null);load()}catch(x){setError((x as Error).message)}}
 async function changeStatus(e:TimelineEvent,status:string){try{const out=await api.updateTimelineEvent(e.id,{status});setSelected(out);load()}catch(x){setError((x as Error).message)}}
 return <><section className="timeline-section"><header className="section-head"><div><span className="eyebrow">CHRONOLOGY · SOURCE BACKED</span><h3>Investigation Timeline <span className="evidence-count">{events?.length??"—"}</span></h3></div><div className="timeline-actions"><button className="button secondary" onClick={()=>setManual(true)}><Plus size={15}/> Add event</button><button className="button" onClick={generate} disabled={busy}><RefreshCw size={15}/>{busy?"Generating…":"Generate timeline"}</button></div></header>
 {notice&&<p className="success">{notice}</p>}{error&&<p className="error">{error}</p>}
 <div className="timeline-toolbar"><label className="evidence-search"><Search size={15}/><input placeholder="Search title, description, location…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{sourceFilters.map(s=><button key={s} className={source===s?"filter active":"filter"} onClick={()=>setSource(s)}>{s==="ALL"?"All":sourceLabel(s)}</button>)}</div><label className="timeline-date-filter">From <input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)}/></label><label className="timeline-date-filter">To <input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)}/></label><div className="filters"><button className={review==="ALL"?"filter active":"filter"} onClick={()=>setReview("ALL")}>All status</button><button className={review==="REVIEW"?"filter active":"filter"} onClick={()=>setReview("REVIEW")}>Needs review</button><button className={review==="DISMISSED"?"filter active":"filter"} onClick={()=>setReview("DISMISSED")}>Dismissed</button></div></div>
 {events===null&&!error&&<div className="loading-box">Loading timeline…</div>}{events?.length===0&&!error&&<div className="empty"><div className="empty-icon"><CalendarClock size={20}/></div><h4>No timeline events yet</h4><p>Generate events from dates explicitly stated in evidence and stored research results, or add an investigator event.</p><button className="button" onClick={generate} disabled={busy}><RefreshCw size={15}/> Generate timeline</button></div>}
 {events&&events.length>0&&<div className="timeline-list">{events.map((e,i)=><article id={`timeline-event-${e.id}`} className="timeline-row" key={e.id}><div className="timeline-axis"><span className={`timeline-dot ${e.source_type?.toLowerCase()||"unknown"}`}/>{i<events.length-1&&<span className="timeline-line"/>}</div><button className="timeline-event-card" onClick={()=>setSelected(e)}><div className="timeline-card-top"><time>{displayDate(e)}</time><span className="precision-tag">{e.date_precision}</span><span className={`source-tag ${e.source_type?.toLowerCase()||"unknown"}`}>{sourceLabel(e.source_type)}</span></div>{issues.filter(x=>x.related_event_id===e.id||x.source_a_id===e.id||x.source_b_id===e.id).map(x=><div className="timeline-conflict-tag" key={x.id}><AlertTriangle size={13}/>{x.type.replaceAll("_"," ")} · <a href={`#contradiction-${x.id}`}>review sources</a></div>)}<h4>{e.title}</h4><p>{e.description||"No description recorded."}</p><div className="timeline-card-meta"><span>{e.event_type.replaceAll("_"," ")}</span><span>{e.status.replaceAll("_"," ")}</span>{e.location&&<span>{e.location}</span>}</div>{e.date_variance.length>0&&<div className="timeline-variance"><AlertTriangle size={15}/> Date variance detected · {e.date_variance.length} other reported date{e.date_variance.length===1?"":"s"}</div>}</button></article>)}</div>}
 {selected&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="dialog timeline-dialog"><header className="dialog-head"><div><span className="eyebrow">TIMELINE EVENT · {sourceLabel(selected.source_type)}</span><h2>{selected.title}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}>×</button></header><div className="timeline-detail-grid"><div><span className="eyebrow">DATE</span><p>{displayDate(selected)}</p></div><div><span className="eyebrow">PRECISION</span><p>{selected.date_precision}</p></div><div><span className="eyebrow">EVENT TYPE</span><p>{selected.event_type.replaceAll("_"," ")}</p></div><div><span className="eyebrow">STATUS</span><p>{selected.status.replaceAll("_"," ")}</p></div><div><span className="eyebrow">LOCATION</span><p>{selected.location||"—"}</p></div><div><span className="eyebrow">IMPORTANCE</span><p>{selected.importance}</p></div></div><h4>Description</h4><p>{selected.description||"No description recorded."}</p><h4>Original date text</h4><p>“{selected.date_text||"Date unavailable"}”</p><h4>Provenance</h4><ul>{selected.sources.map((s,i)=><li key={`${s.source_id}-${i}`}><strong>{s.title||s.source_name||sourceLabel(s.source_type)}</strong> · {s.relationship_type.replaceAll("_"," ")} · {s.source_id}{s.domain&&` · ${s.domain}`}{s.query&&<div>Research query: “{s.query}” · Run {s.research_run_id}</div>}{s.url&&<div><a href={s.url} target="_blank" rel="noreferrer">{s.url}</a></div>}</li>)}</ul>{selected.evidence_ids.length>0&&<p>Evidence: {selected.evidence_ids.map(x=>x.slice(0,8)).join(", ")}</p>}{selected.correlation_ids.length>0&&<p>Related correlations: {selected.correlation_ids.length} · correlations provide context only and do not establish causality.</p>}{selected.publication_date_start&&<p>Source publication date: {selected.publication_date_start} (stored separately from the event date)</p>}{selected.date_variance.length>0&&<div className="timeline-variance"><AlertTriangle size={15}/> Date variance · Requires verification{selected.date_variance.map(v=><p key={v.event_id}>{v.date_text||v.date_start} · {sourceLabel(v.source_type)} · {v.source_id}</p>)}</div>}<div className="form-actions"><a className="button secondary" href={`/investigations/${investigationId}/graph?focus=timeline_event:${selected.id}`}>View in investigation graph</a><select value={selected.status} onChange={e=>changeStatus(selected,e.target.value)}><option value="AI_EXTRACTED">AI extracted</option><option value="REVIEWED">Reviewed</option><option value="DISMISSED">Dismissed</option></select><button className="button secondary" onClick={()=>setEditing(selected)}>Edit event</button><button className="button danger" onClick={()=>remove(selected)}><Trash2 size={14}/> Delete event</button></div></section></div>}
 {manual&&<ManualEvent investigationId={investigationId} close={()=>setManual(false)} done={()=>{setManual(false);load()}}/>}</section>
 {editing&&<EditTimelineEvent event={editing} close={()=>setEditing(null)} done={updated=>{setEditing(null);setSelected(updated);load()}}/>}</>
}
function ManualEvent({investigationId,close,done}:{investigationId:string;close:()=>void;done:()=>void}){
 const [title,setTitle]=useState(""),[description,setDescription]=useState(""),[date,setDate]=useState(""),[location,setLocation]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{await api.createTimelineEvent(investigationId,{title,description,event_type:"INVESTIGATOR_NOTE",date_start:date||null,date_end:date||null,date_precision:date?"EXACT":"UNKNOWN",date_text:date,location:location||null,importance:"MEDIUM"});done()}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 return <div className="overlay"><form className="dialog evidence-form" onSubmit={submit}><header className="dialog-head"><div><span className="eyebrow">INVESTIGATOR PROVIDED</span><h2>Add timeline event</h2></div><button type="button" className="icon-button" onClick={close}>×</button></header><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" disabled={busy}>{busy?"Saving…":"Add event"}</button></div></form></div>
}
function EditTimelineEvent({event,close,done}:{event:TimelineEvent;close:()=>void;done:(event:TimelineEvent)=>void}){
 const [title,setTitle]=useState(event.title),[description,setDescription]=useState(event.description),[dateStart,setDateStart]=useState(event.date_start||""),[dateEnd,setDateEnd]=useState(event.date_end||""),[precision,setPrecision]=useState(event.date_precision),[dateText,setDateText]=useState(event.date_text),[location,setLocation]=useState(event.location||""),[importance,setImportance]=useState(event.importance),[status,setStatus]=useState(event.status),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const updated=await api.updateTimelineEvent(event.id,{title,description,date_start:dateStart||null,date_end:dateEnd||null,date_precision:precision,date_text:dateText,location:location||null,importance,status});done(updated)}catch(x){setError((x as Error).message)}finally{setBusy(false)}}
 return <div className="overlay"><form className="dialog evidence-form" onSubmit={submit}><header className="dialog-head"><div><span className="eyebrow">INVESTIGATOR EDIT</span><h2>Edit timeline event</h2></div><button type="button" className="icon-button" onClick={close}>×</button></header><label>Title<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Description<textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="timeline-detail-grid"><label>Date start<input type="date" value={dateStart} onChange={e=>setDateStart(e.target.value)}/></label><label>Date end<input type="date" value={dateEnd} onChange={e=>setDateEnd(e.target.value)}/><small>Inclusive normalized bounds</small></label><label>Date precision<select value={precision} onChange={e=>setPrecision(e.target.value as TimelineEvent["date_precision"])}>{["EXACT","DAY","MONTH","YEAR","RANGE","APPROXIMATE","UNKNOWN"].map(x=><option key={x}>{x}</option>)}</select></label><label>Original date text<input value={dateText} onChange={e=>setDateText(e.target.value)} maxLength={500}/></label><label>Location<input value={location} onChange={e=>setLocation(e.target.value)}/></label><label>Importance<select value={importance} onChange={e=>setImportance(e.target.value as TimelineEvent["importance"])}>{["LOW","MEDIUM","HIGH"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value as TimelineEvent["status"])}>{["AI_EXTRACTED","INVESTIGATOR_ADDED","REVIEWED","DISMISSED"].map(x=><option key={x}>{x}</option>)}</select></label></div>{error&&<p className="error">{error}</p>}<div className="form-actions"><button type="button" className="button secondary" onClick={close}>Cancel</button><button className="button" disabled={busy}>{busy?"Saving…":"Save event"}</button></div></form></div>
}
