"use client";
import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { ExternalLink, Search, Globe2 } from "lucide-react";
import { api } from "@/lib/api";
import type { Evidence, ResearchRun, ResearchSearchType, ResearchSource } from "@/lib/types";

const types: Array<{ id: ResearchSearchType; label: string }> = [{ id: "WEB", label: "Web" }, { id: "NEWS", label: "Google News" }, { id: "NEWS_TAB", label: "News tab" }, { id: "IMAGE", label: "Images" }];
const maxQueryLength = Number(process.env.NEXT_PUBLIC_MAX_SEARCH_QUERY_LENGTH || 500);

export function WebResearchPanel({ investigationId, evidence, refreshKey = 0 }: { investigationId: string; evidence: Evidence[]; refreshKey?: number }) {
  const [runs, setRuns] = useState<ResearchRun[]>([]); const [sources, setSources] = useState<ResearchSource[]>([]); const [sourceTotal, setSourceTotal] = useState(0); const [sourceOffset, setSourceOffset] = useState(0);
  const [configured, setConfigured] = useState<boolean | null>(null); const [demoMode, setDemoMode] = useState(false); const [selected, setSelected] = useState<string>(""); const [runDetails, setRunDetails] = useState<Record<string, ResearchRun>>({});
  const [usage, setUsage] = useState<{search_count:number;today_search_count:number;result_count:number;successful_search_count:number;failed_search_count:number}|null>(null);
  const [query, setQuery] = useState(""); const [searchType, setSearchType] = useState<ResearchSearchType>("WEB");
  const [filter, setFilter] = useState("ALL"); const [sourceQuery, setSourceQuery] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const refresh = useCallback(async () => {
    const [runPage, sourcePage, usage] = await Promise.all([api.researchRuns(investigationId), api.researchSources(investigationId, sourceQuery, sourceOffset), api.researchUsage(investigationId)]);
    setRuns(runPage.items); setSources(sourcePage.items); setSourceTotal(sourcePage.total); setConfigured(usage.configured); setDemoMode(usage.demo_mode); setUsage(usage);
    setSelected((current) => current && runPage.items.some((run) => run.id === current) ? current : runPage.items[0]?.id || "");
  }, [investigationId, sourceQuery, sourceOffset]);
  useEffect(() => { refresh().catch((e: Error) => setError(e.message)); }, [refresh]);
  useEffect(() => { if (refreshKey) refresh().catch((e: Error) => setError(e.message)); }, [refreshKey, refresh]);
  useEffect(() => { if (selected && !runDetails[selected]) api.researchRun(investigationId, selected).then((run) => setRunDetails((state) => ({ ...state, [selected]: run }))).catch((e: Error) => setError(e.message)); }, [investigationId, selected, runDetails]);
  const active = runDetails[selected] || runs.find((run) => run.id === selected);
  const [resultPage, setResultPage] = useState(0); const [domainFilter, setDomainFilter] = useState(""); const [dateFilter, setDateFilter] = useState("");
  const results = useMemo(() => (active?.searches || []).flatMap((search) => search.results).filter((result) => (filter === "ALL" || result.result_type === filter) && `${result.source?.domain || ""} ${result.source_name || ""}`.toLowerCase().includes(domainFilter.toLowerCase()) && (!dateFilter || (result.published_at || "").toLowerCase().includes(dateFilter.toLowerCase()))), [active, filter, domainFilter, dateFilter]);
  const pageResults = results.slice(resultPage * 20, resultPage * 20 + 20);
  const filteredSources = sources.filter((source) => `${source.title || ""} ${source.domain || ""} ${source.source_name || ""}`.toLowerCase().includes(sourceQuery.toLowerCase()));
  async function execute(action: () => Promise<ResearchRun>, message: string) { setBusy(true); setError(""); setNotice(""); try { const run = await action(); await refresh(); setSelected(run.id); setNotice(message); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function submit(event: FormEvent) { event.preventDefault(); if (!query.trim()) return; void execute(() => api.researchManual(investigationId, query.trim(), searchType), "Search run saved with provider results and provenance."); }
  function evidenceResearch() { void execute(() => api.researchFromEvidence(investigationId, evidence.map((item) => item.id)), "Evidence based research run saved."); }
  return <section className="historical-section web-research-section"><div className="section-head"><div><span className="eyebrow">PUBLIC SOURCE INVESTIGATION</span><h3>Web research</h3></div><span className={demoMode ? "research-state" : configured ? "research-state ready" : "research-state"}>{demoMode ? "DEMO MODE" : configured ? "SERPAPI CONFIGURED" : "SERPAPI KEY REQUIRED"}</span></div>
    <div className="historical-panel"><div className="research-intro"><div><strong>Search public web sources</strong><p>Results are leads for investigator review. They do not independently confirm case evidence.</p>{demoMode&&<strong className="demo-research-label">DEMO SEARCH DATA · NOT LIVE WEB RESULTS</strong>}</div><button className="button" onClick={evidenceResearch} disabled={busy || !evidence.length}>{busy ? "Searching…" : "Research from evidence"}</button></div>
      <form className="research-form" onSubmit={submit}><label className="research-query"><Search size={15}/><input maxLength={maxQueryLength} value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Enter a source search query…"/><span>{query.length}/{maxQueryLength}</span></label><select aria-label="Search type" value={searchType} onChange={(e) => setSearchType(e.target.value as ResearchSearchType)}>{types.map((type) => <option key={type.id} value={type.id}>{type.label}</option>)}</select><button className="button" disabled={busy || !query.trim()}>{busy ? "Searching…" : "Search"}</button></form>
      {error && <p className="error">{error}</p>}{notice && <p className="success">{notice}</p>}
      {usage&&<div className="research-usage"><span>Today · this investigation <strong>{usage.today_search_count}</strong></span><span>This investigation total <strong>{usage.search_count}</strong></span><span>Successful <strong>{usage.successful_search_count}</strong></span><span>Failed <strong>{usage.failed_search_count}</strong></span></div>}
      {!configured && !demoMode && <p className="index-message">Set SERPAPI_API_KEY in the backend environment to enable provider searches. Existing saved research remains available.</p>}
      <div className="research-layout"><aside className="research-runs"><div className="research-subhead"><span className="eyebrow">RUN HISTORY</span><span>{runs.length}</span></div>{runs.length ? runs.map((run) => <button key={run.id} className={selected === run.id ? "research-run active" : "research-run"} onClick={() => setSelected(run.id)}><strong>{run.objective}</strong><small>{run.trigger.replace("_", " ")} · {run.status} · {run.created_at ? new Date(run.created_at).toLocaleString() : ""}</small></button>) : <p className="research-empty">No research runs yet.</p>}</aside>
        <div className="research-detail">{active ? <><div className="research-subhead"><div><span className="eyebrow">SEARCHES AND RESULTS</span><p>{active.evidence.length ? `Initiated from ${active.evidence.map((item) => item.title).join(", ")}` : "Manual investigator query"}</p></div><span>{results.length} results</span></div>
          <div className="filters research-filters">{[{ id: "ALL", label: "All" }, ...types.filter((type) => ["WEB", "NEWS", "IMAGE"].includes(type.id)).map((type) => ({ id: type.id, label: type.label }))].map((tab) => <button key={tab.id} className={filter === tab.id ? "filter active" : "filter"} onClick={() => setFilter(tab.id)}>{tab.label}</button>)}</div>
          {active.searches?.length ? <div className="research-summary">{Number(active.metadata.query_count || 0)} queries · {Number(active.metadata.completed_search_count || 0)} complete · {Number(active.metadata.failed_search_count || 0)} failed · {Number(active.metadata.unique_source_count || 0)} unique sources · Web {Number(active.metadata.web_count || 0)} / News {Number(active.metadata.news_count || 0)} / Images {Number(active.metadata.image_count || 0)}</div> : <p className="research-empty">Loading research details…</p>}
          {(active.searches || []).map((search) => <div className="research-query-record" key={search.id}><div><span className="eyebrow">{search.engine}{search.search_type === "NEWS_TAB" ? " · tbm=nws" : ""} · {search.status}</span><strong>{search.query}</strong><small>{search.result_count} results · {search.serpapi_search_id ? `SerpApi ${search.serpapi_search_id}` : "provider id unavailable"} · {search.serpapi_status || "Provider status unavailable"}{search.search_timestamp ? ` · ${search.search_timestamp}` : ""}</small>{typeof search.parameters.reason === "string"&&<small>{search.parameters.reason}</small>}{search.error_message && <p className="error">{search.error_message}</p>}</div></div>)}
          <div className="research-result-filters"><label>Domain<input value={domainFilter} onChange={(e)=>{setDomainFilter(e.target.value);setResultPage(0)}} placeholder="Filter domain"/></label><label>Published date<input value={dateFilter} onChange={(e)=>{setDateFilter(e.target.value);setResultPage(0)}} placeholder="Filter date text"/></label></div>
          <div className="research-results">{pageResults.length ? pageResults.map((result) => <article className="research-result" key={result.id}>{result.result_type === "IMAGE" && result.thumbnail_url && <img src={result.thumbnail_url} alt="" loading="lazy"/>}<div className="research-result-main"><span className="historical-meta">{result.result_type} · {result.source?.domain || result.source_name || "Source unavailable"}{result.published_at ? ` · ${result.published_at}` : ""}</span><h4>{result.title || "Untitled result"}</h4>{result.snippet && <p>{result.snippet}</p>}{result.url && <a className="source-link" href={result.url} target="_blank" rel="noreferrer">Open source <ExternalLink size={12}/></a>}{result.source && <details className="source-provenance"><summary>Source details · discovered via SerpApi</summary><span>{result.source.canonical_url}</span><small>Discovered from query · {active.searches?.find((search)=>search.id===result.search_id)?.query}</small><small>Search engine · {active.searches?.find((search)=>search.id===result.search_id)?.engine}</small><small>Research run · {active.id}</small><small>First seen · {new Date(result.source.first_seen_at).toLocaleString()}</small><small>Initiated from · {active.evidence.map((item)=>item.title).join(", ")||"Manual query"}</small></details>}</div></article>) : <div className="no-results"><strong>No results in this view.</strong><p>Select another result tab or run a search.</p></div>}</div>
          {results.length>20&&<div className="historical-run"><span>{resultPage*20+1}–{Math.min((resultPage+1)*20,results.length)} of {results.length}</span><div><button className="button secondary" disabled={!resultPage} onClick={()=>setResultPage(resultPage-1)}>Previous</button> <button className="button secondary" disabled={(resultPage+1)*20>=results.length} onClick={()=>setResultPage(resultPage+1)}>Next</button></div></div>}
        </> : <div className="research-placeholder"><Globe2 size={22}/><strong>Select or start a research run</strong><p>Queries, source links, and result details will appear here.</p></div>}</div></div>
      <div className="research-sources"><div className="research-subhead"><div><span className="eyebrow">SAVED SOURCES</span><p>Deduplicated by canonical URL for this investigation</p></div><label className="source-search"><Search size={13}/><input placeholder="Filter sources" value={sourceQuery} onChange={(e) => { setSourceQuery(e.target.value); setSourceOffset(0); }}/></label></div>{filteredSources.length ? <div className="source-list">{filteredSources.map((source) => <div key={source.id} className="saved-source"><a href={source.url} target="_blank" rel="noreferrer"><strong>{source.title || source.domain || source.url}</strong><ExternalLink size={12}/></a><small>{source.domain || ""} · {source.source_type} · {source.result_count} result(s)</small><details className="source-provenance"><summary>Source details</summary><span>{source.canonical_url}</span><small>Source discovered via SerpApi</small><small>First seen · {new Date(source.first_seen_at).toLocaleString()}</small><small>Last seen · {new Date(source.last_seen_at).toLocaleString()}</small></details></div>)}</div> : <p className="research-empty">No saved sources match this filter.</p>}{sourceTotal>25&&<div className="historical-run"><span>{sourceOffset+1}–{Math.min(sourceOffset+25,sourceTotal)} of {sourceTotal}</span><div><button className="button secondary" disabled={sourceOffset===0} onClick={()=>setSourceOffset(Math.max(0,sourceOffset-25))}>Previous</button> <button className="button secondary" disabled={sourceOffset+25>=sourceTotal} onClick={()=>setSourceOffset(sourceOffset+25)}>Next</button></div></div>}</div>
    </div>
  </section>;
}
